#!/usr/bin/env sh
set -eu

# requirements: unzip

# get script path
SCRIPT_DIR=$(cd $(dirname $0); pwd)
cd $SCRIPT_DIR

# ToDo: Arguments
# ToDo: control version by arguments
CPU_TYPE=x86_64
# or aarch64
INSTALL_BASE=${HOME}/LocalApps
INSTALL_PATH=${INSTALL_BASE}/aws-sam-cli
EXECTIVE_PATH=${HOME}/bin

# download
if [ !  -d tmp ]; then
    mkdir tmp
fi
cd tmp
# curl "https://awscli.amazonaws.com/awscli-exe-linux-${CPU_TYPE}.zip" -o "awscliv2.zip"
curl "https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-${CPU_TYPE}.zip" -Lo "aws-sam.zip"

# inflate zip to 'aws/'
unzip aws-sam.zip

# install
if [ ! -d ${INSTALL_PATH}} ]; then
    mkdir -p ${INSTALL_PATH}
fi
./install -i ${INSTALL_PATH} -b ${EXECTIVE_PATH}

# rm trash
rm aws-sam.zip
cd ..
rm -rf tmp/

# finish
echo "Done: install aws-sam-cli"
