#!/usr/bin/env sh
set -eu

# get script path
SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd)"
cd "$SCRIPT_DIR"

VERSION="$(curl --silent "https://api.github.com/repos/mikefarah/yq/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')"
OS=linux
CPU_ARCH="amd64"

INSTALL_PATH="${HOME}/LocalApps"
EXECTIVE_PATH="${HOME}/bin"

PKG="yq_${OS}_${CPU_ARCH}"
DOWNLOAD_URL="https://github.com/mikefarah/yq/releases/download/v${VERSION}/${PKG}"

WORK_DIR="__TMP__"
if [ -d "${WORK_DIR}" ]; then
    rm -rf "${WORK_DIR}"
fi
mkdir "${WORK_DIR}"
cd "${WORK_DIR}"
curl -LO "${DOWNLOAD_URL}"
chmod +x "${PKG}"
mv "${PKG}" "${INSTALL_PATH}/yq"
ln -sfv "${INSTALL_PATH}/yq" "${EXECTIVE_PATH}/yq-go"
ln -sfv "${INSTALL_PATH}/yq" "${EXECTIVE_PATH}/gyq"

# cleanup
cd ..
rm -rf "${WORK_DIR}"

echo "yq(go) v${VERSION} has been installed."
echo "(Please check update by yourself.)"
