#!/usr/bin/env sh
set -eux

# get script path
SCRIPT_DIR=$(cd $(dirname $0); pwd)
cd $SCRIPT_DIR

EXECTIVE_PATH=${HOME}/bin

# unlink
if [ -x ${EXECTIVE_PATH}/bat ]; then
    unlink ${EXECTIVE_PATH}/bat
fi

# install
${SCRIPT_DIR}/install
