#!/usr/bin/env sh
set -eux

# only linux
if [ $(uname) != 'Linux' ]; then
    echo "only works at Linux, sorrry."
    exit 1
fi

# get script path
SCRIPT_DIR=$(cd $(dirname $0); pwd)
cd $SCRIPT_DIR

# ToDo: Arguments
# VERSION=v0.4.4
VERSION=stable
# OS=linux64
INSTALL_PATH=${HOME}/LocalApps/nvim-linux64-stable
EXECUTIVE_PATH=${HOME}/bin

NVIM_APPIMAGE=nvim.appimage
DOWNLOAD_URL=https://github.com/neovim/neovim/releases/download/${VERSION}/${NVIM_APPIMAGE}

# download
curl -LO ${DOWNLOAD_URL}

# install
if [ ! -d ${INSTALL_PATH} ]; then
    mkdir -p ${INSTALL_PATH}
fi
mv ${NVIM_APPIMAGE} ${INSTALL_PATH}
chmod 755 ${INSTALL_PATH}/${NVIM_APPIMAGE}

# make synbolic link
if [ ! -d ${EXECUTIVE_PATH} ]; then
    mkdir -p ${EXECUTIVE_PATH}
fi
ln -snfv ${INSTALL_PATH}/${NVIM_APPIMAGE} ${EXECUTIVE_PATH}/nvim
ln -snfv ${INSTALL_PATH}/${NVIM_APPIMAGE} ${EXECUTIVE_PATH}/nvim-stable
