#cloud-config
# NO-TESTED
timezone: Asia/Tokyo
locale: en_US.utf8
disable_root: True
users:
  - name: orb-user
    ssh_authorized_keys:
      - ssh-ed25519 <EDIT> XXX@YYY
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    groups: adm, sudo, wheel, docker
    uid: 2501
    shell: /usr/bin/fish
# write_files:
#   - path: /path/to/filename
#     append: true
#     content: |
#       line1
#       line2
package_update: true
package_upgrade: true
packages:
  - ubuntu-advantage-tools
  - command-not-found
  - ncurses
  - which
  - less
  - wget
  - curl
  - xz-utils
  - man
  - man-db
  - zip
  - unzip
  # - dos2unix
  # - nkf
  # - p7zip-full
  # - unrar
  - fontconfig
  - fonts-ipafont
  - locales
  - expect
  - jq
  - tree
  - make
  - git
  - tig
  - git-secrets
  - tmux
  - fish
  - zsh
  - nushell
  - bind9-dnsutils
  - net-tools
  - iproute2
  - iputils-ping
  - iputils-clockdiff
  - iputils-arping
  - openssh-server
  - openssh
  - autossh
  - netcat-openbsd
  - ncat
  - htop
  - procs
  - ncdu
  - fzf
  - duf
  - bat
  - ripgrep
  - fd
  - lsd
  - eza
  - git-delta
  - procs
  - hexyl
  - zoxide
  - fuse
  - libfuse2
  # - qemu-user-static
  - vim
  # - neovim
  - mesa-utils-extra
  - x11-apps
  - xauth
  - xclip
  - xsel
  # - podman
  # - podman-compose
  # - uidmap
  - shellcheck
  - shfmt
  - pipx
  # devel
  # - build-essential
  # - llvm
runcmd:
# - sed -i -e 's/^#Port 22/Port 2022/' /etc/ssh/sshd_config
- sed -i -e 's/^#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
- sed -i -e 's/^#X11Forwarding no/X11Forwarding yes/' /etc/ssh/sshd_config
- systemctl enable sshd
- systemctl start sshd

# vim: set ft=yaml ff=unix expandtab ts=2 sw=2
