#!/usr/bin/env sh
set -eu

# get script path
SCRIPT_DIR=$(cd $(dirname $0); pwd)
cd $SCRIPT_DIR

# ToDo: Arguments
VERSION=13.0.0
OS=linux
CPU_TYPE=x86_64
BUILD_TYPE=musl
# or gnu
INSTALL_PATH=${HOME}/LocalApps
EXECTIVE_PATH=${HOME}/bin

PACKAGE="ripgrep-${VERSION}-${CPU_TYPE}-unknown-${OS}-${BUILD_TYPE}"
DOWNLOAD_URL=https://github.com/BurntSushi/ripgrep/releases/download/${VERSION}/${PACKAGE}.tar.gz

# download
curl -LO ${DOWNLOAD_URL}

# install
tar zxvf ${PACKAGE}.tar.gz     # inflate
if [ ! -d ${INSTALL_PATH} ]; then
    mkdir -p ${INSTALL_PATH}
fi

if [ -d ${INSTALL_PATH}/${PACKAGE} ];then
    rm -rf ${INSTALL_PATH}/${PACKAGE}
fi

mv ${PACKAGE} -t ${INSTALL_PATH}

# remove trash
rm ${PACKAGE}.tar.gz

# make synbolic link
ln -sfv ${INSTALL_PATH}/${PACKAGE}/rg ${EXECTIVE_PATH}/rg
